stages:
- stage: 'Build_Stage'
  jobs:
  - job: 'Build_Job'
    pool:
      vmImage: 'windows-2019'

    variables:
      buildConfiguration: 'Release'
      resultName: 'Devopslution'

    steps:
    - task: Npm@1
      displayName: 'Install NPM Packages - $(buildConfiguration)'
      inputs:
        command: 'install' 
        workingDir: Devopslution.Web/

    - script: 'npm run build-$(buildConfiguration)'
      displayName: 'Run Webpack - $(buildConfiguration)'
      workingDirectory: Devopslution.Web/

    - task: DotNetCoreCLI@2
      displayName: '.Net Core Build - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/*.csproj'
        majorVersion: '2' 
        minorVersion: '1' 
        patchVersion: '2'

    - task: DotNetCoreCLI@2
      displayName: '.Net Core Run Tests - $(buildConfiguration)'
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: '.Net Core Publish - $(buildConfiguration)'
      inputs:
        command: publish
        projects: 'Devopslution.Web/Devopslution.Web.csproj'
        publishWebProjects: false
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: True
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: '$(resultName)'


- stage: 'Release_Stage'
  jobs:
  - job: 'Release_Job'
    pool:
      vmImage: 'windows-2019'
    variables:    
      azureSubscription: ''
      azureAppName: 'devopslution'
      resultName: 'Devopslution'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifact'
      inputs:
        artifactName: '$(resultName)'
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Publish Artifact'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Visual Studio Enterprise – MPN (666db697-d4f6-4cd3-ac04-9c0f8f9b7cdc)'
        appType: 'webApp'
        WebAppName: '$(azureAppName)'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
        